import { createFileRoute } from "@tanstack/react-router";
import { ArrowLeftRight, Check, Clipboard, Heart, Loader2, Mic, Play, RotateCcw, Send, Sparkles, Square, Volume2, X } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { PageTitle } from "../components/PageBits";
import { localTranslationService, storage, type ContextKey, type Direction, type HistoryItem, type TranslationFixture } from "../lib/maloom";
import { MAX_TEXT, backendConfigured, transcribeRemote, translateRemote, ClientApiError } from "../lib/maloom-api";
export const Route=createFileRoute("/")({head:()=>({meta:[{title:"معلوم — مترجم عربي مبسّط"},{name:"description",content:"مترجم يساعد على التفاهم بين العربية الواضحة والعربية المبسطة."},{property:"og:title",content:"معلوم — افهم واتفاهم ببساطة"},{property:"og:description",content:"مترجم عربي ثنائي الاتجاه للمواقف اليومية."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Translator});
const contexts:ContextKey[]=["عام","شغل","صيانة","توصيل","تسوّق"];
const flip=(d:Direction):Direction=>d==="pidgin-to-arabic"?"arabic-to-pidgin":"pidgin-to-arabic";
function Wave(){return <div className="wave" aria-hidden="true">{[12,25,18,32,20,27,14].map((h,i)=><i key={i} style={{height:h}}/>)}</div>}
type Rec={phase:"recording"|"review"|"sending";who:"speaker"|"other";url?:string;blob?:Blob};
function Translator(){
 const [mode,setMode]=useState<"محادثة"|"كتابة">("محادثة"),[context,setContext]=useState<ContextKey>("عام"),[direction,setDirection]=useState<Direction>("pidgin-to-arabic"),[text,setText]=useState(""),[result,setResult]=useState<TranslationFixture>(),[unsupported,setUnsupported]=useState(false),[demoRec,setDemoRec]=useState<"speaker"|"other"|null>(null),[simple,setSimple]=useState(false),[copied,setCopied]=useState(false),[favorite,setFavorite]=useState(false),[speechNote,setSpeechNote]=useState("");
 const [live,setLive]=useState<boolean|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(""),[rec,setRec]=useState<Rec|null>(null),[seconds,setSeconds]=useState(0);
 const recorder=useRef<MediaRecorder|null>(null),chunks=useRef<Blob[]>([]),timer=useRef<number|undefined>(undefined);
 const activeDir=rec?.who==="other"?flip(direction):direction;
 const resultDir=result?.direction??direction;
 const sourceLabel=direction==="pidgin-to-arabic"?"عربي مبسّط":"عربي واضح",targetLabel=direction==="pidgin-to-arabic"?"عربي واضح":"عربي مبسّط";
 const rSource=resultDir==="pidgin-to-arabic"?"عربي مبسّط":"عربي واضح",rTarget=resultDir==="pidgin-to-arabic"?"عربي واضح":"عربي مبسّط";
 useEffect(()=>{const settings=storage.read("settings",{largeText:false,autoRead:false});document.documentElement.classList.toggle("large-text",settings.largeText);backendConfigured().then(setLive)},[]);
 useEffect(()=>()=>{stopTracks();window.clearInterval(timer.current)},[]);
 function show(item:TranslationFixture){setResult(item);setText(item.source);setUnsupported(false);setSimple(false);setError("");setFavorite(storage.read<string[]>("favorites",[]).includes(item.id));save(item);const prefs=storage.read("settings",{autoRead:false});if(prefs.autoRead)speak(item.target)}
 async function run(input=text,dir=resultDir){const value=input.trim();if(!value)return;setError("");
  if(live){setLoading(true);try{show(await translateRemote(value,dir,context))}catch(e){if(e instanceof ClientApiError&&e.code==="not_configured"){setLive(false);const out=await localTranslationService.translate(value,dir,context);if(out.fixture)show(out.fixture);else{setResult(undefined);setUnsupported(true)}return}setError(e instanceof ClientApiError?e.message:"حدث خطأ غير متوقع.")}finally{setLoading(false)}return}
  const out=await localTranslationService.translate(value,dir,context);if(out.fixture)show(out.fixture);else{setResult(undefined);setUnsupported(true)}}
 function save(item:TranslationFixture){const history=storage.read<HistoryItem[]>("history",[]);if(history[0]?.source===item.source&&history[0]?.target===item.target)return;storage.write("history",[{...item,id:item.id.startsWith("live-")?item.id:`${item.id}-${Date.now()}`,createdAt:new Date().toISOString(),isUser:true},...history].slice(0,50))}
 function example(){show(localTranslationService.example(context,direction))}
 function swap(){setDirection(flip);setText("");setResult(undefined);setUnsupported(false);setError("")}
 function stopTracks(){recorder.current?.stream.getTracks().forEach(t=>t.stop())}
 async function startRecording(who:"speaker"|"other"){
  setError("");if(!live){setDemoRec(who);return}
  if(typeof window==="undefined"||!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==="undefined"){setError("التسجيل الصوتي غير مدعوم في هذا المتصفح. استخدم وضع الكتابة.");return}
  try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});
   const type=["audio/webm;codecs=opus","audio/webm","audio/mp4","audio/ogg"].find(t=>MediaRecorder.isTypeSupported(t));
   const mr=new MediaRecorder(stream,type?{mimeType:type}:undefined);chunks.current=[];
   mr.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data)};
   mr.onstop=()=>{stream.getTracks().forEach(t=>t.stop());window.clearInterval(timer.current);const blob=new Blob(chunks.current,{type:mr.mimeType||"audio/webm"});chunks.current=[];if(!blob.size){setRec(null);setError("لم يتم التقاط أي صوت.");return}setRec(r=>r&&{...r,phase:"review",blob,url:URL.createObjectURL(blob)})};
   recorder.current=mr;mr.start();setSeconds(0);timer.current=window.setInterval(()=>setSeconds(s=>{if(s>=119){mr.state==="recording"&&mr.stop();}return s+1}),1000);setRec({phase:"recording",who});
  }catch(e){const name=e instanceof Error?e.name:"";setError(name==="NotAllowedError"||name==="SecurityError"?"تم رفض إذن الميكروفون. اسمح به من إعدادات المتصفح أو استخدم وضع الكتابة.":name==="NotFoundError"?"لم يتم العثور على ميكروفون.":"تعذر بدء التسجيل.")}}
 function stopRecording(){if(recorder.current?.state==="recording")recorder.current.stop()}
 function discard(){if(recorder.current?.state==="recording"){recorder.current.onstop=null;recorder.current.stop();stopTracks()}window.clearInterval(timer.current);if(rec?.url)URL.revokeObjectURL(rec.url);setRec(null)}
 async function sendRecording(){if(!rec?.blob)return;const dir=activeDir;setRec({...rec,phase:"sending"});setError("");
  try{const item=await transcribeRemote(rec.blob,dir,context);if(rec.url)URL.revokeObjectURL(rec.url);setRec(null);show(item)}catch(e){setRec({...rec,phase:"review"});setError(e instanceof ClientApiError?e.message:"حدث خطأ غير متوقع.")}}
 function finishDemo(){setDemoRec(null);example()}
 function speak(value:string){if(typeof window==="undefined"||!("speechSynthesis" in window)){setSpeechNote("الاستماع غير مدعوم في هذا المتصفح.");return} window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(value);u.lang="ar";window.speechSynthesis.speak(u);setSpeechNote("جارٍ تشغيل القراءة من المتصفح.")}
 function toggleFav(){if(!result)return;const fs=storage.read<string[]>("favorites",[]);const next=fs.includes(result.id)?fs.filter(x=>x!==result.id):[...fs,result.id];storage.write("favorites",next);setFavorite(next.includes(result.id))}
 function chooseMeaning(choice:string){if(!result)return;const {ambiguity: _ambiguity,...chosen}=result;setResult({...chosen,target:choice})}
 function reset(){setText("");setResult(undefined);setUnsupported(false);setDemoRec(null);discard();setSimple(false);setError("")}
 const micLabel=live?"اضغط للتسجيل":"تسجيل تجريبي";
 return <div><PageTitle eyebrow="كلامك يوصل" title="افهم واتفاهم، ببساطة." description="من العربي إلى الكلام المبسّط… والعكس."/>
  {live===false&&<div className="notice" role="status">وضع العرض التجريبي: خدمة الترجمة غير مهيأة على الخادم، لذا تعمل العبارات الجاهزة فقط.</div>}
  <section className="toolbar" aria-label="خيارات المترجم"><div className="segmented">{(["محادثة","كتابة"] as const).map(x=><button key={x} className={mode===x?"selected":""} onClick={()=>setMode(x)}>{x}</button>)}</div><div className="chips" aria-label="السياق">{contexts.map(x=><button key={x} className={context===x?"chip selected":"chip"} onClick={()=>{setContext(x);setResult(undefined);setText("");setUnsupported(false)}}>{x}</button>)}</div></section>
  <section className="translator-card"><div className="language-row"><span>{sourceLabel}</span><button className="swap-button" onClick={swap} aria-label="عكس اتجاه الترجمة"><ArrowLeftRight size={20}/></button><span>{targetLabel}</span></div>
   {mode==="محادثة"?<div className="mic-grid"><button className="mic-panel primary-mic" disabled={!!rec} onClick={()=>startRecording("speaker")}><span className="mic-orb"><Mic size={28}/></span><strong>أنا أتكلم</strong><small>{micLabel} · {sourceLabel}</small><Wave/></button><button className="mic-panel secondary-mic" disabled={!!rec} onClick={()=>startRecording("other")}><span className="mic-orb"><Mic size={28}/></span><strong>الطرف الثاني</strong><small>{micLabel} · {targetLabel}</small><Wave/></button></div>:<div className="writing-panel"><label htmlFor="translation-input">اكتب العبارة هنا</label><textarea id="translation-input" maxLength={MAX_TEXT} value={text} onChange={e=>{setText(e.target.value);setUnsupported(false)}} placeholder={`اكتب بـ${sourceLabel}…`}/><small className="support-note">{text.length}/{MAX_TEXT}</small><button className="primary-button" disabled={!text.trim()||loading} onClick={()=>run(text,direction)}>{loading?<Loader2 size={18} className="animate-spin"/>:<Sparkles size={18}/>}{loading?"جارٍ الترجمة…":"اعرض المعنى"}</button></div>}
   <div className="example-row"><button className="outline-button" onClick={example}><Play size={17}/>جرّب مثالًا جاهزًا</button><button className="quiet-button" onClick={reset}><RotateCcw size={17}/>محادثة جديدة</button></div>
   {rec&&<div className="recording-box" aria-live="polite">{rec.phase==="recording"?<><div><span className="record-dot"/><strong>جارٍ التسجيل… {seconds} ث</strong><p>{rec.who==="speaker"?"أنت تتكلم":"الطرف الثاني يتكلم"}. التسجيل لا يُحفظ.</p></div><div className="flex gap-2"><button className="icon-button" onClick={discard} aria-label="إلغاء التسجيل"><X size={19}/></button><button className="stop-button" onClick={stopRecording}><Square size={15} fill="currentColor"/>إيقاف</button></div></>:<><div className="w-full"><strong>راجع التسجيل قبل الإرسال</strong>{rec.url&&<audio controls src={rec.url} className="mt-2 w-full"/>}</div><div className="flex gap-2"><button className="icon-button" onClick={discard} disabled={rec.phase==="sending"} aria-label="حذف التسجيل"><X size={19}/></button><button className="stop-button" onClick={sendRecording} disabled={rec.phase==="sending"}>{rec.phase==="sending"?<Loader2 size={15} className="animate-spin"/>:<Send size={15}/>}{rec.phase==="sending"?"جارٍ التفريغ والترجمة…":"فرّغ وترجم"}</button></div></>}</div>}
   {demoRec&&<div className="recording-box"><div><span className="record-dot"/><strong>تسجيل تجريبي</strong><p>الخدمة غير مهيأة؛ هذا عرض للتفاعل فقط ولا يستخدم الميكروفون.</p></div><div className="flex gap-2"><button className="icon-button" onClick={()=>setDemoRec(null)} aria-label="إلغاء التسجيل"><X size={19}/></button><button className="stop-button" onClick={finishDemo}><Square size={15} fill="currentColor"/>إيقاف واستخدام المثال</button></div></div>}
   {error&&<div className="notice" role="alert">{error}</div>}
   {unsupported&&<div className="notice">الترجمة الفعلية غير مهيأة على هذا الخادم. جرّب إحدى العبارات الجاهزة حاليًا.</div>}
  </section>
  {result&&<section className="results" aria-live="polite"><article className="result-card"><div className="result-heading"><span>الكلام الأصلي{result.id.startsWith("live-")?"":" · مثال جاهز"}</span><span>{rSource}</span></div><textarea value={text} maxLength={MAX_TEXT} onChange={e=>setText(e.target.value)} aria-label="تعديل الكلام الأصلي"/><button className="small-action" disabled={loading} onClick={()=>run(text,resultDir)}>{loading?<Loader2 size={16} className="animate-spin"/>:<Check size={16}/>}تحديث</button></article><article className="result-card result-accent"><div className="result-heading"><span>المعنى</span><span>{rTarget}</span></div>{result.ambiguity&&!simple?<div><h3 className="mb-3 font-bold">تقصد أي معنى؟</h3>{result.ambiguity.map(choice=><button className="choice" key={choice} onClick={()=>chooseMeaning(choice)}>{choice}<ArrowLeftRight size={15}/></button>)}</div>:<p className="result-text">{simple&&result.simpler?result.simpler:result.target}</p>}<div className="actions"><button onClick={()=>navigator.clipboard?.writeText(simple&&result.simpler?result.simpler:result.target).then(()=>setCopied(true))} aria-label="نسخ"><Clipboard size={18}/><span>{copied?"تم النسخ":"نسخ"}</span></button><button onClick={toggleFav} className={favorite?"active":""} aria-label="إضافة للمفضلة"><Heart size={18}/><span>حفظ</span></button><button onClick={()=>speak(simple&&result.simpler?result.simpler:result.target)} aria-label="استماع"><Volume2 size={18}/><span>استماع</span></button>{result.simpler&&<button onClick={()=>setSimple(!simple)}><Sparkles size={18}/><span>{simple?"النص الكامل":"بسّط أكتر"}</span></button>}</div>{speechNote&&<p className="support-note">{speechNote}</p>}</article></section>}
  <section className="recent-preview"><div><span className="eyebrow">مثال جاهز</span><h2>محادثة قصيرة</h2></div><div className="conversation"><p>بكرة إنت يجي ساعة تسعة، يجيب ورقة معاك</p><p>تعال غدًا الساعة التاسعة، وأحضر الورقة معك.</p></div></section>
 </div>}
